### ISSUE TITLE
automate creation of CHANGELOG.md and/or releases

### ISSUE THREAD

**Issue by tjstansell** [Twingate/terraform-provider-twingate#244]
The last 2 releases for this provider haven't included great changelogs.  v0.2.2 only mentioned a doc update, but actually included support for locations in remote networks as well (which was broken).  v0.2.3 was just released and mentions the fix for location, but the release doesn't include links to the PR.  Neither of these follow the release formatting done previously.  Perhaps some automation would be better suited for release management and ideally a running CHANGELOG.md could be built so that it's easy to see the history of changes instead of having to browse the github releases?  I would suggest looking at adopting Hashicorp's go-changelog, like AWS has used:

https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/workflows/generate_changelog.yml

Any other solution would be fine if it provides more complete and consistent changelogs to see what has changed between releases.

**Comment by alexmensch** [comment]
Yeah, the `v0.2.2` release had a long delay on release notes, that's on us on the process we're using. We use the existing auto-generated Github release notes, which are then manually edited for public clarity afterwards. That's how all previous releases have been done.

We're looking at changing the process now so that we don't do a release before notes are ready/updated.
