### ISSUE TITLE
release `v0.3.0` broke `twingate_groups` data source

### ISSUE THREAD

**Issue by tjstansell** [Twingate/terraform-provider-twingate#274]
I tried updating to the `v0.3.0` release and go the following error during a plan:
```
│ Error: failed to read group with id All: 'NoneType' object has no attribute 'items'
│
│   with data.twingate_groups.active,
│   on main.tf line 594, in data "twingate_groups" "active":
│  594: data "twingate_groups" "active" {
```
and the code itself is just:
```hcl
data "twingate_groups" "active" {
  is_active = true
}
```

I tried running terraform with debug logs, but it did not produce any additional information related to this.
```
Terraform v1.3.7
on linux_arm64
+ provider registry.terraform.io/hashicorp/archive v2.3.0
+ provider registry.terraform.io/hashicorp/aws v4.53.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/twingate/twingate v0.3.0
```

**Comment by alexmensch** [comment]
Hi @tjstansell we're working on a fix now. The source of the issue isn't in the provider, but in our API, so once it's fixed, the provider will work as expected. In v0.3.0 we updated the provider to use server-side group filtering (instead of within the client), and that exposed a small bug on the server side. We'll update this issue again when it's resolved.

**Comment by alexmensch** [comment]
@tjstansell should be fixed on our side now. Let me know and we can close this out / investigate further as appropriate?

**Comment by tjstansell** [comment]
Thanks! I'll test it out in just a bit.

**Comment by tjstansell** [comment]
Yup.  This issue seems to be resolved.  Thanks!
