### ISSUE TITLE
Fix dependency between service accounts and service keys when applying changes

### ISSUE THREAD

**Issue by alexmensch** [Twingate/terraform-provider-twingate#407]
Below are details on where I ran into this problem in a Terraform configuration. Let me know if you need more information.

`terraform plan` wanted to leave a service key in place, and then change the parent service account, but that’s actually not allowed by Twingate.

I got this error on run: `Error: failed to delete service account with id abcde: Github CI/CD contains 1 active keys that must be revoked first.`

And this is what plan said:

```Terraform will perform the following actions:

  # module.cluster.twingate_resource.cluster will be updated in-place
  ~ resource "twingate_resource" "cluster" {
        id                          = "UmVzb3VyY2U6MjMzNzUzOA=="
        name                        = "GKE Cluster"
        # (6 unchanged attributes hidden)

      ~ access {
          ~ service_account_ids = [] -> (known after apply)
            # (1 unchanged attribute hidden)
        }

        # (1 unchanged block hidden)
    }

  # module.cluster.twingate_service_account.github_actions will be created
  + resource "twingate_service_account" "github_actions" {
      + id   = (known after apply)
      + name = "Github CI/CD"
    }

  # module.gitops.twingate_service_account.github_actions will be destroyed
  # (because twingate_service_account.github_actions is not in configuration)
  - resource "twingate_service_account" "github_actions" {
      - id   = "U2VydmljZUFjY291bnQ6MTJkZmFhMjQtNTQyYi00YzZjLTg5YWUtZWEyMmIzMmMzYzJj" -> null
      - name = "Github CI/CD" -> null
    }

  # module.gitops.twingate_service_account_key.github_actions_key will be updated in-place
  ~ resource "twingate_service_account_key" "github_actions_key" {
        id                 = "U2VydmljZUFjY291bnRLZXk6c0Y2T0VRdFphRE83TkF6MWtOdVo1c2ktR3YzR25TZklDUHNlTGRZVU9Baw=="
        name               = "rustling-scorpion"
      ~ service_account_id = "U2VydmljZUFjY291bnQ6MTJkZmFhMjQtNTQyYi00YzZjLTg5YWUtZWEyMmIzMmMzYzJj" -> (known after apply)
        # (1 unchanged attribute hidden)
    }

Plan: 1 to add, 2 to change, 1 to destroy.
```

So what we should be doing here is destroying the key, too, and then recreating the key and service account per the changes in the configuration.

To fix this, I have to manually delete the service account key.

**Comment by tjstansell** [comment]
This looks like you renamed a resource inside of terraform, which is causing it to delete the old one and create a new one.  In this case, you could just tell terraform you moved it so it doesn't think it needs to delete/create new ones...
```hcl
moved {
  from = module.gitops.twingate_service_account.github_actions
  to   = module.cluster.twingate_service_account.github_actions
}
```
That said, if you try to delete a `twingate_service_account` with active keys, I wonder if it should _always_ delete all keys? or only if something like `force_destroy` is enabled for the service account (similar in principal to the relationship between `aws_iam_user` and `aws_iam_access_key` resources?

**Comment by tjstansell** [comment]
Or perhaps the `twingate_service_account_key` resource just needs to mark the `service_account_id` attribute as requiring replacement if it ever changes and terraform would properly handle all the delete/recreate ordering...

**Comment by ekampf** [comment]
@tjstansell Thanks! but we think what happens here is as follows:
Basically the issue is `ServiceAccountKey` is a child of `ServiceAccount` - if the parent get deleted all its children get deleted too.
So the problem here is that TF is trting to re-create the service account, and change the key's `service_account_id` to point to this new SA.
That's incorrect, it should delete and recreate the key in this case too...

**Comment by tjstansell** [comment]
> That's incorrect, it should delete and recreate the key in this case too...

Isn't that what terraform would do if the `service_account_id` argument in the keys resource is defined to force recreation on change? I don't like the fact that the way the current PR is written, there no way to control whether a service account deletion should be able to force delete keys. It's fine to allow it, because perhaps you don't use terraform to create the keys. I just think there should be an attribute to enable the key deletions, but it should not be the default behavior.

**Comment by ekampf** [comment]
@tjstansell the way the system is implemented, the keys are __owned__ by the service account (they would not have any meaning - permissions - on their own). 
They are not an entity on their own that can move between service accounts.
A service account deletion by definition deletes its keys
In the Admin UI, we wont let you delete a service account if it has active keys (you have to disable\delete all of them first) but I dont think something like that would work well for TF.

**Comment by ekampf** [comment]
@tjstansell I think we have a misunderstanding of the problem.
The issue repro here as I understand it is this:
1. Create an SA + key in TF
2. Go to Admin UI, revoke the key and delete the SA
3. Run TF - it has the wrong idea of what happened - it thinks the key is still around and only the SA needs to be recreated when in fact they're both gone

**Comment by tjstansell** [comment]
I think we disagree on what happened in the original description. :)  

The terraform output shows
```
  # module.cluster.twingate_service_account.github_actions will be created
...
  # module.gitops.twingate_service_account.github_actions will be destroyed
```
which implies to me that the original terraform code renamed a module from `gitops` to `cluster`.  This causes terraform to want to delete the old resource name and create a new one.  It's my understanding the service account (and keys) still exist.  The result of this action is the plan expects the service account id to change.  This service account id is used in the key resource, but the key resource doesn't think it needs to recreate the key if the id changes, it's just going to do an "update".  That's not valid or correct and is what's leading to all the other errors.
```
  ~ resource "twingate_service_account_key" "github_actions_key" {
        id                 = "U2VydmljZUFjY291bnRLZXk6c0Y2T0VRdFphRE83TkF6MWtOdVo1c2ktR3YzR25TZklDUHNlTGRZVU9Baw=="
        name               = "rustling-scorpion"
      ~ service_account_id = "U2VydmljZUFjY291bnQ6MTJkZmFhMjQtNTQyYi00YzZjLTg5YWUtZWEyMmIzMmMzYzJj" -> (known after apply)
        # (1 unchanged attribute hidden)
    }
```

I'm postulating that if the `service_account_id` argument in the `twingate_service_account_key` resource correctly marked itself as `RequiresReplace`, then the plan would have correctly created a new replacement key resource and then deleted the old key _prior_ to trying to delete the old service account because of the dependency between the two.

I've simulated this locally by using:
```hcl
resource "twingate_service_account" "github_actions" {
  name = "Github CI/CD"
}

resource "terraform_data" "sa_id" {
  input = twingate_service_account.github_actions.id
}

resource "twingate_service_account_key" "github_actions_key" {
  service_account_id = twingate_service_account.github_actions.id

  lifecycle {
    replace_triggered_by = [terraform_data.sa_id.input]
  }
}
```
and then modifying it to rename the service account resource ...
```diff
1,2c1,2
< resource "twingate_service_account" "github_actions" {
<   name = "Github CI/CD"
---
> resource "twingate_service_account" "github_actions2" {
>   name = "Github CI/CD 2"
6c6
<   input = twingate_service_account.github_actions.id
---
>   input = twingate_service_account.github_actions2.id
10c10
<   service_account_id = twingate_service_account.github_actions.id
---
>   service_account_id = twingate_service_account.github_actions2.id
```
If I run it _without_ the lifecycle block, I get the same error as Alex reports:
```
twingate_service_account.github_actions2: Destroying... [id=U2VydmljZUFjY291bnQ6NmI3NzRjOTYtOTQ2OC00OGE2LTgxNjUtY2I1ZDU3YTFkZWJi]
twingate_service_account.github_actions: Creating...
twingate_service_account.github_actions: Creation complete after 1s [id=U2VydmljZUFjY291bnQ6MGNjMDJmYTktNmIxNy00OTI1LTg0NDktN2Y5ZGU5MTkzNGE5]
╷
│ Error: failed to delete twingate_service_account
│
│ failed to delete service account with id U2VydmljZUFjY291bnQ6NmI3NzRjOTYtOTQ2OC00OGE2LTgxNjUtY2I1ZDU3YTFkZWJi: Github CI/CD 2 contains 1 active keys that must be revoked first.
```
However, if I run it with the lifecycle block, it behaves as it should:
```
twingate_service_account_key.github_actions_key: Destroying... [id=U2VydmljZUFjY291bnRLZXk6dklmT1QwT201YWh4UTF6bVZXekhmajFEOWtpc3NnNjRZclgxcTJ0amxIZw==]
twingate_service_account_key.github_actions_key: Destruction complete after 2s
twingate_service_account.github_actions: Destroying... [id=U2VydmljZUFjY291bnQ6MGNjMDJmYTktNmIxNy00OTI1LTg0NDktN2Y5ZGU5MTkzNGE5]
twingate_service_account.github_actions2: Creating...
twingate_service_account.github_actions2: Creation complete after 1s [id=U2VydmljZUFjY291bnQ6Yjg5MTg4NGItNjU1OS00ZTRiLTlmZmEtMzdhZmMwYTdjNTZj]
twingate_service_account.github_actions: Destruction complete after 1s
terraform_data.sa_id: Modifying... [id=ca811910-10b9-e68b-6df7-f387b90bc1bc]
terraform_data.sa_id: Modifications complete after 0s [id=ca811910-10b9-e68b-6df7-f387b90bc1bc]
twingate_service_account_key.github_actions_key: Creating...
twingate_service_account_key.github_actions_key: Creation complete after 1s [id=U2VydmljZUFjY291bnRLZXk6VmhBbmgxU01xWmtXRzIxSHFVRDlpS0RnekxNR1F2WE1ia1R3QjRFQk5pQQ==]

Apply complete! Resources: 2 added, 1 changed, 2 destroyed.
``` 

This then leads me to the second part of this discussion, which is related to having the `twingate_service_account` resource actually delete keys when it is being deleted.
- If you're managing these things entirely with terraform, then terraform _should_ be deleting the key resource first because of dependencies and it shouldn't be needed.
- If you're creating service accounts in terraform and then someone is manually creating keys for those (or rotating them or whatever), then you probably don't want terraform to be able to delete the service account (and hence the keys) if it still has active keys.
- Similarly, even if you _think_ you manage everything in terraform, I might not want a service account deleted (and it's keys) if there was a rogue key manually created.  This would mimic the UI behavior.
- Then again, you might make the argument that everything should be in terraform and if something was done outside of it, it should be removed.

The point here is that it should be up to the user to decide which use-case they're in and which behavior they want to see.  This is generally done via an additional argument on the service account resource, like `force_destroy` (e.g. [aws_iam_user](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_user#force_destroy) allows this, but `google_service_account` will delete the service account regardless if it has any keys).

**Comment by tjstansell** [comment]
I'll point out that automatically deleting keys when deleting the service account should be considered a breaking change and you can avoid that by simply adding a `force_destroy` argument so folks can opt-in to this new behavior.  Easier on folks.

**Comment by ekampf** [comment]
Interesting...  will check this scenario.
But regarding your last 4 bullet points I think they're all correct and also how the system should behave today.

- The API already mimics the UI behavior - if you try to delete an SA with active keys the mutation will fail
- So if you created an SA in TF and then a bunch of keys manually - TF wont have them in its state and wont try to revoke them when deleting the SA and when it makes the API call to delete it will fail
- If you manage everything in TF and there are no external keys it doesn't know of - when deleting the SA it should revoke the keys to allow that deletion to happen

**Comment by tjstansell** [comment]
> But regarding your last 4 bullet points I think they're all correct and also how the system should behave today.

Correct.  I was concerned by the initial state of PR #415 that was going to automatically revoke keys when a service account was being deleted.  That looks to have been reverted and now the PR just fixes the `service_account_id` argument to `RequiresReplace`.  I think the only question is if you want to add the ability to opt into deleting a service account with active keys _not_ managed by terraform (hence my `force_delete` suggestion)?

**Comment by ekampf** [comment]
@tjstansell but that behavior was still per what you described - TF only revokes the keys it knows, if there's any key created outside of TF it will not be revoked and deletion would fail

**Comment by tjstansell** [comment]
[This change](https://github.com/Twingate/terraform-provider-twingate/pull/415/commits/101b25b1b8e4e1d3e45bda9e5b113facbe720b1c#diff-1a700af5300de8e26e53376eda618ef774a744cff97e8c585cea59b5204ea044R74-R87) would have revoked _all_ keys.  That was my initial concern.

**Comment by ekampf** [comment]
Ok, so I was misunderstanding the issue.
The issue here is that we have a Service Account and a key managed in TF.
Alex moved the SA to a different module so TF sees this is deletion of the SA and recreating it in the new module.
This SA recreation should trigger recreating the key - the fix we just merged (based on your suggestion :) ) does just that.
