### ISSUE TITLE
Error when terraforming wildcard resources, address considered invalid

### ISSUE THREAD

**Issue by robotparty** [Twingate/terraform-provider-twingate#446]
We are trying to add a wildcard resource like `*.example.com` and are getting an error that the resource address is invalid. 
We can add an identical resource via the web console with no issues.
we're using 1.2.6

**Comment by ekampf** [comment]
@robotparty can you share some more information: Whats the error message you're seeing?  Can you share a snippet of your TF code to crate said resource?

**Comment by robotparty** [comment]
The terraform apply error: 
```
Run terraform apply -auto-approve workspace.plan
module.twingate_resources.twingate_resource.current["int-prod-jumpcloud"]: Creating...
╷
│ Error: failed to create resource: Alias must be a valid DNS name
│ 
│   with module.twingate_resources.twingate_resource.current["int-prod-jumpcloud"],
│   on modules/twingate_resources/resources.tf line 50, in resource "twingate_resource" "current":
│   50: resource "twingate_resource" "current" {
│ 
╵
Error: Process completed with exit code 1.
```

**Comment by robotparty** [comment]
Ah I think I see the issue... a wildcard resource is not a browser address, it's a `standard address` which doesn't support aliases?

**Comment by robotparty** [comment]
I was able to fix the issue by adding a ternary condition to set alias only when `*` is not present in the address:
`alias             = (strcontains(each.value.address, "*") == true ? null : each.value.address)`

The TF applied ok and the resource looked good. Will let you know if issues come up later.

**Comment by alexb-twingate** [comment]
@robotparty - I can add some more detail on why the alias leads to an error. Aliases don't currently support wildcards because we don't have a way to map a wildcard in one string to another. For example, we don't have any logic to map `*.domain.example` to `*.alias.example`. All types of Resources (browser addresses, standard addresses and even background addresses) all support aliases.

If that would be useful to you, let me know!
