### ISSUE TITLE
Request: Expose IP adress on twingate_connector

### ISSUE THREAD

**Issue by krokofant** [Twingate/terraform-provider-twingate#587]
This will make it easier to configure firewall exceptions for external IPs of the connectors. Instead of depending on the deployment platform to fetch these it would be convenient to expose them on the twingate_connector resource, as it is represented in the Twingate UI.

**Comment by alexb-twingate** [comment]
Hi @krokofant - when you say the deployment platform, do you mean GCP, AWS, etc.? To me, it feels like their public IP would be the source of truth and it should be given by whichever provider you're using from your VMs. 

Twingate is pulling the public IP based on what we see. However, the VM's public IP in Terraform would be much more accurate.

**Comment by alexb-twingate** [comment]
Are you deploying to GCP, AWS, Azure, etc. via Terraform as well? If you are, most have convenient ways to get the public IP of the VM that you've deployed. Your cloud's public IP address is going to be a better source of truth than Twingate will be.

Could you tell me more about what you're trying to do? How are you deploying things, are you just reading information instead of deploying it in Terraform, etc.

**Comment by alexb-twingate** [comment]
Will be solved by #605

**Comment by krokofant** [comment]
> Will be solved by #605

Great!
