### ISSUE TITLE
Add data source: twingate_remote_network

### ISSUE THREAD

**Issue by bertekintw** [Twingate/terraform-provider-twingate#64]
Arguments

- (Required) `id`
    - This ID can be obtained either directly from the public admin API or referenced via the `twingate_remote_networks` data source in our Provider.

Exported attributes

- `id` (String)
- `name` (String)

GraphQL

```graphql
query {
  remoteNetwork(id:"UmVtb3RlTmV0d29yazoyMg==")
   {
    id
		name
  }
}
```

**Comment by alexmensch** [comment]
> hey @alexmensch can you check description, when we fetching remote-network by id in result I'd expected single object - not a list, and description says - A list of remote_networks

Yeah, you're absolutely right. Let me see what happened—I think it might have been a copy & paste error across all the different issue descriptions—but I'll update the description to make sure that the PR ultimately matches the issue.

**Comment by alexmensch** [comment]
Updated @vmanilo!

**Comment by vmanilo** [comment]
@alexmensch please update description according to new plans

**Comment by alexmensch** [comment]
In closing #103 due to the controller change, we still need a way to find a remote network based on its name, which is the most important part of the new data sources. I'm closing this issue with the release of provider v1.0.8, and opening up a different issue to add a name lookup for a single remote network.
